# Generated by Django 6.0.1 on 2026-01-21 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_liveclass_attendance'),
        ('core', '0003_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificates/templates/backgrounds/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificates/templates/logos/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificates/templates/signatures/')),
                ('title_text', models.CharField(default='Certificate of Completion', max_length=255)),
                ('body_text', models.TextField(default='This is to certify that {student_name} has successfully completed the course {course_name}.')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='core.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='ISSUED', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/generated/')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='academics.course')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='academics.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.certificatetemplate')),
            ],
        ),
    ]
