# Generated by Django 6.0.1 on 2026-01-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_calendarevent'),
        ('core', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_profile', models.URLField(blank=True, max_length=500)),
                ('experience', models.TextField(blank=True)),
                ('current_employer_university', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='admissions/photos/')),
                ('resume_cv', models.FileField(upload_to='admissions/resumes/')),
                ('guardian_type', models.CharField(max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('father_phone', models.CharField(blank=True, max_length=20)),
                ('father_occupation', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('mother_phone', models.CharField(blank=True, max_length=20)),
                ('mother_occupation', models.CharField(blank=True, max_length=255)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_relation', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_occupation', models.CharField(blank=True, max_length=255)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_address', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='academics.course')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='core.institute')),
            ],
        ),
    ]
