# Generated by Django 6.0.1 on 2026-01-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_studentadmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/photos/'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='resume_cv',
            field=models.FileField(blank=True, null=True, upload_to='admissions/resumes/'),
        ),
    ]
