# Generated by Django 6.0.1 on 2026-01-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_studentadmission_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='academics.batch'),
        ),
    ]
