# Generated by Django 6.0 on 2026-01-25 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_studentadmission_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.course'),
        ),
    ]
