# Generated by Django 6.0 on 2026-01-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_calendarevent_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='academics.question'),
        ),
    ]
