# Generated by Django 6.0 on 2026-01-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_gradechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Assignment'), ('PRE_ASSESSMENT', 'Pre-Assessment'), ('POST_ASSESSMENT', 'Post-Assessment')], default='REGULAR', max_length=20),
        ),
    ]
