# Generated by Django 6.0 on 2026-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_assignment_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_percentage',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Quiz'), ('PRE_ASSESSMENT', 'Pre-Assessment'), ('POST_ASSESSMENT', 'Post-Assessment')], default='REGULAR', max_length=20),
        ),
    ]
