# Generated by Django 6.0 on 2026-01-27 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_quiz_passing_percentage_quiz_quiz_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive (Absent)'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_INSTRUCTOR', 'Pending Instructor Review'), ('PENDING_ADMIN', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_INSTRUCTOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor_comment', models.TextField(blank=True)),
                ('admin_comment', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_applications', to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='PRESENT', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Attendance',
                'unique_together': {('student', 'course', 'date')},
            },
        ),
    ]
