# Generated by Django 6.0 on 2026-01-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_documentgalleryitem_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='course_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=10),
        ),
    ]
