# Generated by Django 6.0 on 2026-01-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_studentadmission_course_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
    ]
