# Generated by Django 6.0.1 on 2026-01-21 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='trophy', max_length=50)),
                ('criteria_type', models.CharField(choices=[('XP', 'XP Threshold'), ('LESSONS', 'Lessons Completed'), ('STREAK', 'Daily Streak'), ('MANUAL', 'Manual Award')], default='XP', max_length=20)),
                ('criteria_value', models.IntegerField(default=0)),
                ('xp_bonus', models.PositiveIntegerField(default=0)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.institute')),
            ],
        ),
        migrations.CreateModel(
            name='GamificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('xp_per_login', models.PositiveIntegerField(default=10)),
                ('xp_per_lesson', models.PositiveIntegerField(default=50)),
                ('xp_per_assignment_submission', models.PositiveIntegerField(default=100)),
                ('xp_per_assignment_score_perfect', models.PositiveIntegerField(default=50)),
                ('xp_per_quiz_attempt', models.PositiveIntegerField(default=20)),
                ('xp_per_quiz_score_per_point', models.PositiveIntegerField(default=1)),
                ('xp_per_attendance', models.PositiveIntegerField(default=30)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_settings', to='core.institute')),
            ],
        ),
        migrations.CreateModel(
            name='UserGamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_history', to='gamification.usergamificationprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='gamification.usergamificationprofile')),
            ],
            options={
                'unique_together': {('profile', 'badge')},
            },
        ),
    ]
