# Generated by Django 6.0.1 on 2026-01-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('INSTITUTE_ADMIN', 'Institute Admin'), ('INSTRUCTOR', 'Instructor'), ('STUDENT', 'Student'), ('ALUMNI', 'Alumni'), ('EMPLOYER', 'Employer')], default='STUDENT', max_length=20),
        ),
    ]
