# Generated by Django 6.0 on 2026-01-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_instructorinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instructor_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
