# Generated by Django 6.0 on 2026-01-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_instructor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
