# Generated by Django 6.0 on 2026-01-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_institute_contact_email_institute_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_mode',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=10, null=True),
        ),
    ]
