# Generated by Django 6.0 on 2026-02-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_course_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('INSTITUTE_ADMIN', 'Institute Admin'), ('HR', 'HR'), ('INSTRUCTOR', 'Instructor'), ('EMPLOYEE', 'Employee'), ('STUDENT', 'Student'), ('ALUMNI', 'Alumni'), ('EMPLOYER', 'Employer')], default='STUDENT', max_length=20),
        ),
    ]
